# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TodoList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ObjectMapper', '~> 2.2'
  # Pods for TodoList

end

target 'TodoFramework' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'
    # Pods for TodoList
    
end
