# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WhoToFollow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya-ObjectMapper/RxSwift'

  # Pods for WhoToFollow

  target 'WhoToFollowTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
  end

  target 'WhoToFollowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
